# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright @ Harry Yang & 2017 - 2022 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
########################################################

datasource:
  url: jdbc:mysql://localhost:3306/today?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true
  username: your db user
  password: your db password
  driverClassName: com.mysql.cj.jdbc.Driver
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    maxLifetime: 1800000
    maxPoolSize: 20

site:
  host: your host like 'https://taketoday.cn'
  upload: /data/docs/
  uploadPath: file:///${site.serverPath}/upload/
  app:
    path: /server/api
  admin:
    assets:
      path: file://assets/admin/

  ######################################## github login

github:
  app-id:
  app-key:
  callback: ${site.host}/api/auth/github/callback
  redirect: https://github.com/login/oauth/authorize?client_id=${github.appId}&scope=user:email&state=

gitee:
  app-id:
  app-key:
  callback: ${site.host}/api/auth/gitee/callback
  redirect: https://gitee.com/oauth/authorize?client_id=${gitee.appId}&response_type=code&state=
