# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright @ Harry Yang & 2017 - 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
########################################################

datasource:
  username: your db user
  password: your db password

site:
  host: your host like 'https://taketoday.cn'

  ######################################## github login

github:
  app-id:
  app-key:
  callback: ${site.host}/api/auth/github/callback
  redirect: https://github.com/login/oauth/authorize?client_id=${github.appId}&scope=user:email&state=

gitee:
  app-id:
  app-key:
  callback: ${site.host}/api/auth/gitee/callback
  redirect: https://gitee.com/oauth/authorize?client_id=${gitee.appId}&response_type=code&state=
