# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright @ Harry Yang & 2017 - 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
########################################################

server:
  session:
    timeout: 3D
  netty:
    worker-threads: 8
    acceptor-threads: 1
    logging-level: debug

datasource:
  username: root
  password: 88888888

  #jdbc.pool.isReadOnly    = false
  #jdbc.pool.idleTimeout   = 600000
  #jdbc.username           = ${jdbc.userName}
  #jdbc.driverClassName    = ${jdbc.driver}
  #jdbc.pool.connectionTimeout = 30000

site:
  #aliyun.oss.enable=false
  host: http://localhost:8080

aliyun:
  oss:
    enabled: false

######################################## github login
github:
  app-id:
  app-key:
  callback: ${site.host}/api/auth/github/callback
  redirect: https://github.com/login/oauth/authorize?client_id=${github.appId}&scope=user:email&state=

gitee:
  app-id:
  app-key:
  callback: ${site.host}/api/auth/gitee/callback
  redirect: https://gitee.com/oauth/authorize?client_id=${gitee.appId}&response_type=code&state=

web:
  mvc:
    log-request-details: true

app:
  main:
    lazy-initialization: false

logging:
  level:
    netty: debug
    nettyLogging: debug
#    web: debug
#    sql: debug