# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright @ Harry Yang & 2017 - 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
########################################################

app:
  name: today-blog-api

server:
  session:
    cookie:
      http-only: true
      secure: true
      max-age: 1d
      same-site: lax
  netty:
    worker-threads: 8
    acceptor-threads: 1
    leak-detection: disabled
    connection-timeout: 10s
    auto-ack-ping-frame: true
    auto-ack-settings-frame: true
    http2-graceful-shutdown-timeout: 29s
    auto-read: ${server.http2.enabled}

  use-virtual-thread-service-executor: true

  http2:
    enabled: false
    initial-settings:
      max-header-list-size: 1024
      push-enabled: false
      connect-protocol-enabled: false

infra:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev

freemarker:
  cache: false
  settings:
    classic_compatible: true
    date_format: yyyy-MM-dd
    datetime_format: yyyy-MM-dd HH:mm:ss
    default_encoding: UTF-8
    locale: UTF-8
    log_template_exceptions: false
    number_format: 0.####
    tag_syntax: auto_detect
    template_exception_handler: ignore
    template_update_delay: 0
    time_format: HH:mm:ss
    url_escaping_charset: UTF-8

jackson:
  time-zone: UTC
  date-format: 'yyyy-MM-dd HH:mm:ss'
  deserialization:
    # 常用,json中含pojo不存在属性时是否失败报错,默认true
    FAIL_ON_UNKNOWN_PROPERTIES: false
  serialization:
    FAIL_ON_EMPTY_BEANS: false # 对象为空时是否报错，默认true


aliyun:
  oss:
    accessKeyId:
    bucket:
    enabled: false
    endpoint:
    secretAccessKey:

mail:
  username: 1
  password: 1
  protocol: smtp
  host: smtp.qq.com
  port: 465
  ssl:
    enabled: true
  properties:
    mail:
      smtp:
        auth: true
        connectionTimeout: 5000
        writeTimeout: 5000
        timeout: 3000

site:
  subTitle: 代码是我心中的一首诗
  version: v3.1

datasource:
  name: 'blog-datasource'

flyway:
  baseline-version: 3.1.0
  baseline-on-migrate: true
  baseline-description: baseline
  sql-migration-prefix: v
  table: schema_history

logging:
  file:
    path: ./logs
  level:
    root: info
  group:
    blog: cn.taketoday.blog
    netty: io.netty
    nettyLogging: io.netty.handler.logging