# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright @ Harry Yang & 2017 - 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
########################################################

app:
  name: today-blog-api

server:
  session:
    cookie:
      http-only: true
      secure: true
      max-age: 1d
      same-site: lax
    persistent: true
  multipart:
    max-file-size: 20MB
    max-request-size: 100MB
    file-size-threshold: 512MB

infra:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev

freemarker:
  cache: false
  settings:
    classic_compatible: true
    date_format: yyyy-MM-dd
    datetime_format: yyyy-MM-dd HH:mm:ss
    default_encoding: UTF-8
    locale: UTF-8
    log_template_exceptions: false
    number_format: 0.####
    tag_syntax: auto_detect
    template_exception_handler: ignore
    template_update_delay: 0
    time_format: HH:mm:ss
    url_escaping_charset: UTF-8

jackson:
  #  time-zone: GMT+8
  date-format: 'yyyy-MM-dd HH:mm:ss'
  deserialization:
    # 常用,json中含pojo不存在属性时是否失败报错,默认true
    FAIL_ON_UNKNOWN_PROPERTIES: false
  serialization:
    WRITE_DATES_AS_TIMESTAMPS: false # 返回的java.util.date转换成timestamp
    FAIL_ON_EMPTY_BEANS: false # 对象为空时是否报错，默认true


aliyun:
  oss:
    accessKeyId:
    bucket:
    enabled: false
    endpoint:
    secretAccessKey:

mail:
  debug: false
  from:
    userName:
  nickName:
  password:
  smtp:
    auth: true
    host: smtp.qq.com
    port: 465
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
    ssl:
      enable: true
    timeout: 25000
  transport:
    protocol: smtp
  userName:

site:
  subTitle: 代码是我心中的一首诗
  version: v3.1

datasource:
  name: 'blog-datasource'
  url: jdbc:mysql://localhost:3306/today?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  type: com.zaxxer.hikari.HikariDataSource
  username: root
  password: 88888888
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 20
    max-lifetime: 120000
    connection-test-query: 'select 1'

logging:
  file:
    path: ./logs
  level:
    root: info
  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
  group:
    blog: cn.taketoday.blog
    netty: io.netty
    nettyLogging: io.netty.handler.logging