# Original Author -> Harry Yang (taketoday@foxmail.com) https://taketoday.cn
# Copyright @ Harry Yang & 2017 - 2023 All Rights Reserved.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER
########################################################

server:
  session:
    timeout: 3D
    persistent: true
  netty:
    worker-threads: 8
    acceptor-threads: 1
    max-connection: 10240000
    leak-detection: paranoid
    connection-timeout: 30s
    auto-ack-ping-frame: true
    auto-ack-settings-frame: true
    http2-graceful-shutdown-timeout: 29s
    auto-read: ${server.http2.enabled}

  use-virtual-thread-service-executor: true

  http2:
    enabled: false
    initial-settings:
      max-header-list-size: 1024
      push-enabled: false
      connect-protocol-enabled: false

datasource:
  username: root
  password: 88888888
  url: jdbc:mysql://localhost:3306/today?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 20
    max-lifetime: 120000
    connection-test-query: 'select 1'

site:
  #aliyun.oss.enable=false
  host: http://localhost:8080

aliyun:
  oss:
    enabled: false


web:
  error:
    include-message: always
  mvc:
    log-request-details: true

infra:
  task:
    execution:
      thread-name-prefix: app-pool-
      pool:
        max-size: 100

app:
  main:
    lazy-initialization: false

logging:
  level:
    netty: info
    nettyLogging: info
    web: debug
    sql: debug
    infra:
      app:
        availability: debug

  pattern:
    dateformat: 'yyyy-MM-dd HH:mm:ss.SSS'
